# _PIP_ADDITIONAL_REQUIREMENTS=$_PIP_ADDITIONAL_REQUIREMENTS
# AIRFLOW_UID=$AIRFLOW_UID

export DBT_PROFILES_DIR=$DBT_PROFILES_DIR

export SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT  # account identifier=org-account
export SNOWFLAKE_USER=$SNOWFLAKE_USER
export SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
export SNOWFLAKE_ROLE=$SNOWFLAKE_ROLE
export SNOWFLAKE_DATABASE=$SNOWFLAKE_DATABASE
export SNOWFLAKE_WAREHOUSE=$SNOWFLAKE_WAREHOUSE
export SNOWFLAKE_SCHEMA=$SNOWFLAKE_SCHEMA
